package pool

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	defaultNomadVersion   = "2.0.4"
	defaultTraefikVersion = "3.7.7"
)

type RenderedFile struct {
	Path    string
	Content string
}

func ControlPlaneNode(cfg Config) (Node, bool) {
	for _, node := range cfg.Nodes {
		if node.Role == "control-plane" {
			return node, true
		}
	}
	return Node{}, false
}

func RenderControlPlane(cfg Config) ([]RenderedFile, error) {
	node, ok := ControlPlaneNode(cfg)
	if !ok {
		return nil, fmt.Errorf("config has no control-plane node")
	}
	if node.OverlayIP == "" {
		return nil, fmt.Errorf("control-plane node %q is missing overlay_ip", node.Name)
	}
	if node.PublicIP == "" {
		return nil, fmt.Errorf("control-plane node %q is missing public_ip", node.Name)
	}
	if node.SSHUser == "" {
		return nil, fmt.Errorf("control-plane node %q is missing ssh_user", node.Name)
	}
	if node.SSHKey == "" {
		return nil, fmt.Errorf("control-plane node %q is missing ssh_key", node.Name)
	}

	files := []RenderedFile{
		{Path: "bootstrap-control-plane.sh", Content: renderBootstrapScript(node)},
		{Path: "nomad/server.hcl", Content: renderNomadServer(node)},
		{Path: "systemd/nomad.service", Content: renderNomadService()},
		{Path: "traefik/traefik.yml", Content: renderTraefikStatic(node)},
		{Path: "systemd/traefik.service", Content: renderTraefikService()},
		{Path: "wireguard/wg0.conf", Content: renderWireGuard(node)},
		{Path: "systemd/poolctl-guard.service", Content: renderGuardService()},
		{Path: "systemd/poolctl-guard.timer", Content: renderGuardTimer()},
	}
	return files, nil
}

func RenderAppJob(cfg Config, appName string) (RenderedFile, error) {
	app, ok := cfg.FindApp(appName)
	if !ok {
		return RenderedFile{}, fmt.Errorf("unknown app %q", appName)
	}
	if app.Image == "" {
		return RenderedFile{}, fmt.Errorf("app %q is missing image", app.Name)
	}
	if app.Domain == "" {
		return RenderedFile{}, fmt.Errorf("app %q is missing domain", app.Name)
	}
	if app.Port == 0 {
		return RenderedFile{}, fmt.Errorf("app %q is missing port", app.Name)
	}
	target, ok := cfg.FindNode(app.PreferNode)
	if !ok {
		return RenderedFile{}, fmt.Errorf("app %q targets unknown node %q", app.Name, app.PreferNode)
	}
	if target.OverlayIP == "" {
		return RenderedFile{}, fmt.Errorf("target node %q is missing overlay_ip", target.Name)
	}

	return RenderedFile{
		Path:    filepath.Join("nomad", "jobs", app.Name+".nomad.hcl"),
		Content: renderNomadJob(app),
	}, nil
}

func RenderWorkerJoin(control, worker Node, controlPublicKey string) ([]RenderedFile, error) {
	if control.OverlayIP == "" {
		return nil, fmt.Errorf("control-plane node %q is missing overlay_ip", control.Name)
	}
	if control.PublicIP == "" {
		return nil, fmt.Errorf("control-plane node %q is missing public_ip", control.Name)
	}
	if worker.Name == "" {
		return nil, fmt.Errorf("worker node is missing name")
	}
	if worker.OverlayIP == "" {
		return nil, fmt.Errorf("worker node %q is missing overlay_ip", worker.Name)
	}
	if worker.PublicIP == "" {
		return nil, fmt.Errorf("worker node %q is missing public_ip", worker.Name)
	}
	if controlPublicKey == "" {
		return nil, fmt.Errorf("control-plane WireGuard public key is missing")
	}

	return []RenderedFile{
		{Path: "bootstrap-worker.sh", Content: renderWorkerBootstrapScript(control, worker, controlPublicKey)},
		{Path: "nomad/client.hcl", Content: renderNomadClient(control, worker)},
		{Path: "systemd/nomad.service", Content: renderNomadService()},
	}, nil
}

func WriteRendered(base string, files []RenderedFile) error {
	for _, file := range files {
		target := filepath.Join(base, file.Path)
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		mode := os.FileMode(0o644)
		if strings.HasSuffix(file.Path, ".sh") {
			mode = 0o755
		}
		if err := os.WriteFile(target, []byte(file.Content), mode); err != nil {
			return err
		}
	}
	return nil
}

func CopyLocalBinaryIntoBundle(base string) (bool, error) {
	const localBinary = "work/poolctl"
	data, err := os.ReadFile(localBinary)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	target := filepath.Join(base, "poolctl")
	if err := os.WriteFile(target, data, 0o755); err != nil {
		return false, err
	}
	return true, nil
}

func renderBootstrapScript(node Node) string {
	return fmt.Sprintf(`#!/usr/bin/env bash
set -Eeuo pipefail

# Generated by poolctl for %s.
# Review before running on a fresh Ubuntu 22.04+ ARM64 control-plane VM.

NOMAD_VERSION="${NOMAD_VERSION:-%s}"
TRAEFIK_VERSION="${TRAEFIK_VERSION:-%s}"
NOMAD_ADDR="https://%s:4646"
POOLCTL_STATE_DIR="/var/lib/poolctl"
POOLCTL_READY_MARKER="$POOLCTL_STATE_DIR/control-plane.ready"
NOMAD_ACL_DIR="$POOLCTL_STATE_DIR/nomad-acl"
NOMAD_BOOTSTRAP_TOKEN_FILE="$NOMAD_ACL_DIR/bootstrap.token"
NOMAD_BOOTSTRAP_JSON_FILE="$NOMAD_ACL_DIR/bootstrap-token.json"
NOMAD_TRAEFIK_TOKEN=""

die() {
  echo "ERROR: $*" >&2
  exit 1
}

trap 'echo "ERROR: bootstrap failed near line $LINENO: $BASH_COMMAND" >&2' ERR

require_root() {
  if [ "$(id -u)" -eq 0 ]; then
    SUDO=""
  else
    SUDO="sudo"
  fi
}

ensure_iptables_accept() {
  proto="$1"
  port="$2"
  comment="$3"

  if $SUDO iptables -C INPUT -p "$proto" -m state --state NEW --dport "$port" -m comment --comment "$comment" -j ACCEPT 2>/dev/null; then
    return
  fi

  reject_line="$($SUDO iptables -L INPUT --line-numbers -n | awk '$2 == "REJECT" { print $1; exit }')"
  if [ -n "$reject_line" ]; then
    $SUDO iptables -I INPUT "$reject_line" -p "$proto" -m state --state NEW --dport "$port" -m comment --comment "$comment" -j ACCEPT
  else
    $SUDO iptables -A INPUT -p "$proto" -m state --state NEW --dport "$port" -m comment --comment "$comment" -j ACCEPT
  fi
}

ensure_host_ingress_firewall() {
  ensure_iptables_accept tcp 80 poolctl-ingress-http
  ensure_iptables_accept tcp 443 poolctl-ingress-https
  ensure_iptables_accept udp 51820 poolctl-wireguard

  if command -v netfilter-persistent >/dev/null 2>&1; then
    $SUDO netfilter-persistent save || true
  elif command -v iptables-save >/dev/null 2>&1 && $SUDO test -d /etc/iptables; then
    $SUDO sh -c 'iptables-save > /etc/iptables/rules.v4'
  fi
}

detect_arch() {
  case "$(uname -m)" in
    aarch64|arm64) echo "arm64" ;;
    x86_64|amd64) echo "amd64" ;;
    *) die "unsupported architecture: $(uname -m)" ;;
  esac
}

install_zip_binary() {
  name="$1"
  version="$2"
  url="$3"
  sums_url="$4"
  archive="$5"
  binary="$6"

  tmp_dir="$(mktemp -d)"
  trap 'rm -rf "$tmp_dir"' RETURN

  curl -fsSL "$url" -o "$tmp_dir/$archive"
  curl -fsSL "$sums_url" -o "$tmp_dir/SHA256SUMS"
  (cd "$tmp_dir" && grep "  $archive$" SHA256SUMS | sha256sum -c -) || die "$name checksum verification failed"
  unzip -q "$tmp_dir/$archive" -d "$tmp_dir/$name"
  $SUDO install -m 0755 "$tmp_dir/$name/$binary" "/usr/local/bin/$name"
  "$name" version || true
}

install_tar_binary() {
  name="$1"
  version="$2"
  url="$3"
  sums_url="$4"
  archive="$5"
  binary="$6"

  tmp_dir="$(mktemp -d)"
  trap 'rm -rf "$tmp_dir"' RETURN

  curl -fsSL "$url" -o "$tmp_dir/$archive"
  curl -fsSL "$sums_url" -o "$tmp_dir/SHA256SUMS"
  (cd "$tmp_dir" && grep "  $archive$" SHA256SUMS | sha256sum -c -) || die "$name checksum verification failed"
  tar -xzf "$tmp_dir/$archive" -C "$tmp_dir"
  $SUDO install -m 0755 "$tmp_dir/$binary" "/usr/local/bin/$name"
  "$name" version || true
}

render_wireguard_config() {
  $SUDO install -d -m 0700 /etc/wireguard
  if [ ! -f /etc/wireguard/poolctl-control.key ]; then
    wg genkey | $SUDO tee /etc/wireguard/poolctl-control.key >/dev/null
    $SUDO chmod 0600 /etc/wireguard/poolctl-control.key
  fi
  private_key="$($SUDO cat /etc/wireguard/poolctl-control.key)"
  $SUDO install -m 0600 /dev/null /etc/wireguard/wg0.conf
  $SUDO tee /etc/wireguard/wg0.conf >/dev/null <<WGEOF
[Interface]
Address = %s/24
ListenPort = 51820
PrivateKey = $private_key

# Worker peers are appended by poolctl join-node.
WGEOF
  $SUDO systemctl enable wg-quick@wg0
  $SUDO systemctl restart wg-quick@wg0
}

render_nomad_tls() {
  $SUDO install -d -m 0750 -o nomad -g nomad /etc/nomad.d/tls
  tls_tmp="$(mktemp -d)"
  trap '$SUDO rm -rf "$tls_tmp"' RETURN
  if [ ! -f /etc/nomad.d/tls/nomad-agent-ca-key.pem ]; then
    openssl genrsa -out "$tls_tmp/nomad-agent-ca-key.pem" 4096
    openssl req -x509 -new -nodes -key "$tls_tmp/nomad-agent-ca-key.pem" -sha256 -days 3650 \
      -subj "/CN=poolctl-nomad-agent-ca" -out "$tls_tmp/nomad-agent-ca.pem"
    $SUDO install -m 0600 -o root -g root "$tls_tmp/nomad-agent-ca-key.pem" /etc/nomad.d/tls/nomad-agent-ca-key.pem
    $SUDO install -m 0644 -o nomad -g nomad "$tls_tmp/nomad-agent-ca.pem" /etc/nomad.d/tls/nomad-agent-ca.pem
  fi

  cat >"$tls_tmp/nomad-server.cnf" <<EOF
[req]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[dn]
CN = server.global.nomad

[req_ext]
subjectAltName = @alt_names

[alt_names]
DNS.1 = server.global.nomad
DNS.2 = localhost
IP.1 = 127.0.0.1
IP.2 = %s
EOF

  openssl genrsa -out "$tls_tmp/global-server-nomad-key.pem" 2048
  openssl req -new -key "$tls_tmp/global-server-nomad-key.pem" -out "$tls_tmp/global-server-nomad.csr" -config "$tls_tmp/nomad-server.cnf"
  $SUDO openssl x509 -req -in "$tls_tmp/global-server-nomad.csr" \
    -CA /etc/nomad.d/tls/nomad-agent-ca.pem \
    -CAkey /etc/nomad.d/tls/nomad-agent-ca-key.pem \
    -CAcreateserial -out "$tls_tmp/global-server-nomad.pem" -days 825 -sha256 \
    -extensions req_ext -extfile "$tls_tmp/nomad-server.cnf"

  $SUDO install -m 0640 -o nomad -g nomad "$tls_tmp/global-server-nomad-key.pem" /etc/nomad.d/tls/global-server-nomad-key.pem
  $SUDO install -m 0644 -o nomad -g nomad "$tls_tmp/global-server-nomad.pem" /etc/nomad.d/tls/global-server-nomad.pem
}

nomad_cli() {
  token="$(read_nomad_token || true)"
  if [ -n "$token" ]; then
    $SUDO env NOMAD_ADDR="$NOMAD_ADDR" NOMAD_CACERT="/etc/nomad.d/tls/nomad-agent-ca.pem" NOMAD_TOKEN="$token" nomad "$@"
  else
    $SUDO env NOMAD_ADDR="$NOMAD_ADDR" NOMAD_CACERT="/etc/nomad.d/tls/nomad-agent-ca.pem" nomad "$@"
  fi
}

read_nomad_token() {
  for file in "$NOMAD_BOOTSTRAP_TOKEN_FILE" /etc/nomad.d/bootstrap.token /etc/nomad.d/acl/bootstrap.token; do
    if [ -s "$file" ]; then
      token="$($SUDO awk 'NF { print; exit }' "$file")"
      if [ -n "$token" ]; then
        printf '%%s\n' "$token"
        return 0
      fi
    fi
  done
  return 0
}

parse_nomad_secret_id() {
  $SUDO sed -n 's/.*"SecretID"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p; s/.*"SecretId"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p; s/.*"secret_id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$1" | head -1
}

write_nomad_bootstrap_json() {
  output="$1"
  printf '%%s\n' "$output" | $SUDO tee "$NOMAD_BOOTSTRAP_JSON_FILE" >/dev/null
  $SUDO chmod 0600 "$NOMAD_BOOTSTRAP_JSON_FILE"
}

migrate_nomad_acl_files() {
  $SUDO install -d -m 0700 -o root -g root "$NOMAD_ACL_DIR"

  for token_file in "$NOMAD_BOOTSTRAP_TOKEN_FILE" /etc/nomad.d/bootstrap.token /etc/nomad.d/acl/bootstrap.token; do
    [ -f "$token_file" ] || continue
    if ! $SUDO awk 'NF { found=1 } END { exit found ? 0 : 1 }' "$token_file"; then
      $SUDO mv "$token_file" "$NOMAD_ACL_DIR/empty-token.$(basename "$token_file").$(date +%%s)"
    fi
  done

  for legacy_json in /etc/nomad.d/bootstrap-token.json /etc/nomad.d/acl/bootstrap-token.json; do
    [ -f "$legacy_json" ] || continue
    if [ ! -f "$NOMAD_BOOTSTRAP_JSON_FILE" ]; then
      $SUDO mv "$legacy_json" "$NOMAD_BOOTSTRAP_JSON_FILE"
      $SUDO chmod 0600 "$NOMAD_BOOTSTRAP_JSON_FILE"
    else
      $SUDO mv "$legacy_json" "$NOMAD_ACL_DIR/bootstrap-token.legacy.$(date +%%s).json"
    fi
  done

  for legacy_token in /etc/nomad.d/bootstrap.token /etc/nomad.d/acl/bootstrap.token; do
    if [ -f "$legacy_token" ] && [ ! -f "$NOMAD_BOOTSTRAP_TOKEN_FILE" ]; then
      $SUDO install -m 0600 -o root -g root "$legacy_token" "$NOMAD_BOOTSTRAP_TOKEN_FILE"
    fi
  done

  if [ -f "$NOMAD_BOOTSTRAP_JSON_FILE" ] && [ ! -f "$NOMAD_BOOTSTRAP_TOKEN_FILE" ]; then
    token="$(parse_nomad_secret_id "$NOMAD_BOOTSTRAP_JSON_FILE")"
    [ -n "$token" ] && echo "$token" | $SUDO tee "$NOMAD_BOOTSTRAP_TOKEN_FILE" >/dev/null
    [ -f "$NOMAD_BOOTSTRAP_TOKEN_FILE" ] && $SUDO chmod 0600 "$NOMAD_BOOTSTRAP_TOKEN_FILE"
  fi
}

forget_saved_nomad_tokens() {
  stamp="$(date +%%s)"
  for token_file in "$NOMAD_BOOTSTRAP_TOKEN_FILE" /etc/nomad.d/bootstrap.token /etc/nomad.d/acl/bootstrap.token; do
    [ -f "$token_file" ] || continue
    safe_name="$(basename "$token_file")"
    $SUDO mv "$token_file" "$NOMAD_ACL_DIR/invalid-token.$safe_name.$stamp"
  done
}

nomad_token_can_read_services() {
  token="$1"
  tmp_body="$(mktemp)"
  http_code="$($SUDO curl -fsS -o "$tmp_body" -w '%%{http_code}' \
    --cacert /etc/nomad.d/tls/nomad-agent-ca.pem \
    -H "X-Nomad-Token: $token" \
    "$NOMAD_ADDR/v1/services" 2>/dev/null || true)"
  $SUDO rm -f "$tmp_body"
  [ "$http_code" = "200" ]
}

restart_nomad_or_die() {
  reason="$1"
  if ! $SUDO systemctl restart nomad; then
    print_nomad_diagnostics
    die "failed to restart Nomad: $reason"
  fi
}

archive_nomad_server_state_for_bootstrap() {
  if [ -f "$POOLCTL_READY_MARKER" ]; then
    die "Nomad ACL token is missing after control plane was marked ready; refusing to archive server state automatically"
  fi

  stamp="$(date -u +%%Y%%m%%d%%H%%M%%S)"
  echo "Archiving interrupted Nomad server state to /opt/nomad/server.bootstrap-recovery.$stamp."
  $SUDO systemctl stop nomad || true
  $SUDO rm -f /opt/nomad/acl-bootstrap-reset /opt/nomad/server/acl-bootstrap-reset || true
  if [ -d /opt/nomad/server ]; then
    $SUDO mv /opt/nomad/server "/opt/nomad/server.bootstrap-recovery.$stamp"
  fi
  restart_nomad_or_die "fresh bootstrap after interrupted ACL setup"
  wait_for_nomad
}

run_nomad_acl_bootstrap() {
  if output="$(nomad_cli acl bootstrap -json 2>&1)"; then
    write_nomad_bootstrap_json "$output"
    return
  fi

  reset_index="$(printf '%%s\n' "$output" | sed -n 's/.*reset index: \([0-9][0-9]*\).*/\1/p' | head -1)"
  if [ -z "$reset_index" ]; then
    printf '%%s\n' "$output" >&2
    die "failed to bootstrap Nomad ACL"
  fi

  echo "Nomad ACL is already bootstrapped but no local token was found; resetting bootstrap with reset index $reset_index."
  $SUDO install -d -m 0700 -o root -g root /opt/nomad/server
  printf '%%s\n' "$reset_index" | $SUDO tee /opt/nomad/acl-bootstrap-reset >/dev/null
  printf '%%s\n' "$reset_index" | $SUDO tee /opt/nomad/server/acl-bootstrap-reset >/dev/null
  $SUDO chmod 0600 /opt/nomad/acl-bootstrap-reset
  $SUDO chmod 0600 /opt/nomad/server/acl-bootstrap-reset
  restart_nomad_or_die "ACL bootstrap reset"
  wait_for_nomad

  output="$(nomad_cli acl bootstrap -json 2>&1)" || {
    printf '%%s\n' "$output" >&2
    print_nomad_diagnostics
    echo "Reset-file recovery did not produce a bootstrap window; falling back to interrupted-bootstrap state archive."
    archive_nomad_server_state_for_bootstrap
    output="$(nomad_cli acl bootstrap -json 2>&1)" || {
      printf '%%s\n' "$output" >&2
      print_nomad_diagnostics
      die "failed to bootstrap Nomad ACL after archiving interrupted server state"
    }
  }
  $SUDO rm -f /opt/nomad/acl-bootstrap-reset
  $SUDO rm -f /opt/nomad/server/acl-bootstrap-reset
  write_nomad_bootstrap_json "$output"
}

print_nomad_diagnostics() {
  echo "---- nomad systemd status ----"
  $SUDO systemctl status nomad --no-pager -l || true
  echo "---- nomad journal ----"
  $SUDO journalctl -u nomad -n 120 --no-pager || true
  echo "---- wg0 address ----"
  ip addr show wg0 || true
  echo "---- listening ports ----"
  $SUDO ss -ltnp | grep -E ':(4646|4647|4648)\b' || true
}

wait_for_nomad() {
  for _ in $(seq 1 45); do
    if $SUDO systemctl is-active --quiet nomad; then
      if nomad_cli status >/dev/null 2>&1; then
        return
      fi
      leader="$($SUDO curl -fsS --cacert /etc/nomad.d/tls/nomad-agent-ca.pem "$NOMAD_ADDR/v1/status/leader" 2>/dev/null || true)"
      if [ -n "$leader" ]; then
        return
      fi
    fi
    sleep 2
  done
  print_nomad_diagnostics
  die "Nomad did not become ready on $NOMAD_ADDR"
}

bootstrap_nomad_acl() {
  migrate_nomad_acl_files
  existing_token="$(read_nomad_token)"
  if [ -n "$existing_token" ] && nomad_token_can_read_services "$existing_token"; then
    NOMAD_TRAEFIK_TOKEN="$existing_token"
    return
  fi
  if [ -n "$existing_token" ]; then
    echo "Saved Nomad token cannot read /v1/services; recovering ACL bootstrap token."
    forget_saved_nomad_tokens
  fi
  wait_for_nomad
  run_nomad_acl_bootstrap
  token="$(parse_nomad_secret_id "$NOMAD_BOOTSTRAP_JSON_FILE")"
  if [ -z "$token" ]; then
    echo "Could not parse SecretID from Nomad ACL bootstrap output:" >&2
    $SUDO sed -n '1,80p' "$NOMAD_BOOTSTRAP_JSON_FILE" >&2 || true
    die "failed to parse Nomad bootstrap token"
  fi
  echo "$token" | $SUDO tee "$NOMAD_BOOTSTRAP_TOKEN_FILE" >/dev/null
  $SUDO chmod 0600 "$NOMAD_BOOTSTRAP_TOKEN_FILE"
  validate_nomad_token "$token"
  NOMAD_TRAEFIK_TOKEN="$token"
}

validate_nomad_token() {
  token="$1"
  tmp_body="$(mktemp)"
  http_code="$($SUDO curl -fsS -o "$tmp_body" -w '%%{http_code}' \
    --cacert /etc/nomad.d/tls/nomad-agent-ca.pem \
    -H "X-Nomad-Token: $token" \
    "$NOMAD_ADDR/v1/services" 2>/dev/null || true)"
  if [ "$http_code" != "200" ]; then
    echo "Nomad token validation failed for /v1/services with HTTP $http_code" >&2
    $SUDO cat "$tmp_body" >&2 || true
    $SUDO rm -f "$tmp_body"
    die "Traefik cannot use the saved Nomad token"
  fi
  $SUDO rm -f "$tmp_body"
}

render_traefik_config() {
  token="$NOMAD_TRAEFIK_TOKEN"
  if [ -z "$token" ]; then
    token="$(read_nomad_token)"
  fi
  [ -n "$token" ] || die "Nomad token is empty; cannot render Traefik config"
  validate_nomad_token "$token"
  $SUDO install -d -m 0750 -o traefik -g traefik /etc/traefik /var/lib/traefik
  if [ ! -f /var/lib/traefik/acme.json ]; then
    $SUDO install -m 0600 -o traefik -g traefik /dev/null /var/lib/traefik/acme.json
  else
    $SUDO chown traefik:traefik /var/lib/traefik/acme.json
    $SUDO chmod 0600 /var/lib/traefik/acme.json
  fi
  $SUDO install -m 0644 -o traefik -g traefik /etc/nomad.d/tls/nomad-agent-ca.pem /etc/traefik/nomad-agent-ca.pem
  $SUDO install -m 0640 -o root -g traefik /dev/null /etc/traefik/traefik.yml
  $SUDO tee /etc/traefik/traefik.yml >/dev/null <<TRAEFIKEOF
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  nomad:
    endpoint:
      address: "$NOMAD_ADDR"
      token: "$token"
      tls:
        ca: "/etc/traefik/nomad-agent-ca.pem"
    exposedByDefault: false

api:
  dashboard: false

certificatesResolvers:
  letsencrypt:
    acme:
      storage: "/var/lib/traefik/acme.json"
      httpChallenge:
        entryPoint: web
TRAEFIKEOF
  $SUDO chown root:traefik /etc/traefik/traefik.yml
  $SUDO chmod 0640 /etc/traefik/traefik.yml
}

require_root
ARCH="$(detect_arch)"

$SUDO apt-get update
$SUDO env DEBIAN_FRONTEND=noninteractive apt-get install -y curl unzip ca-certificates gnupg lsb-release ufw wireguard openssl tar iptables-persistent

# Docker is used by Nomad's docker task driver.
if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | $SUDO sh
  $SUDO usermod -aG docker %s
fi

$SUDO useradd --system --home /etc/nomad.d --shell /usr/sbin/nologin nomad 2>/dev/null || true
$SUDO useradd --system --home /etc/traefik --shell /usr/sbin/nologin traefik 2>/dev/null || true

NOMAD_ARCHIVE="nomad_${NOMAD_VERSION}_linux_${ARCH}.zip"
NOMAD_URL="https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/${NOMAD_ARCHIVE}"
NOMAD_SUMS_URL="https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_SHA256SUMS"
install_zip_binary "nomad" "$NOMAD_VERSION" "$NOMAD_URL" "$NOMAD_SUMS_URL" "$NOMAD_ARCHIVE" "nomad"

TRAEFIK_ARCHIVE="traefik_v${TRAEFIK_VERSION}_linux_${ARCH}.tar.gz"
TRAEFIK_URL="https://github.com/traefik/traefik/releases/download/v${TRAEFIK_VERSION}/${TRAEFIK_ARCHIVE}"
TRAEFIK_SUMS_URL="https://github.com/traefik/traefik/releases/download/v${TRAEFIK_VERSION}/traefik_v${TRAEFIK_VERSION}_checksums.txt"
install_tar_binary "traefik" "$TRAEFIK_VERSION" "$TRAEFIK_URL" "$TRAEFIK_SUMS_URL" "$TRAEFIK_ARCHIVE" "traefik"

render_wireguard_config
render_nomad_tls

$SUDO install -d -m 0750 -o nomad -g nomad /etc/nomad.d /opt/nomad
$SUDO install -d -m 0700 -o root -g root "$POOLCTL_STATE_DIR" "$NOMAD_ACL_DIR"
$SUDO install -d -m 0750 -o traefik -g traefik /etc/traefik /var/lib/traefik
$SUDO install -m 0640 -o nomad -g nomad nomad/server.hcl /etc/nomad.d/server.hcl
$SUDO install -m 0644 systemd/nomad.service /etc/systemd/system/nomad.service
$SUDO install -m 0640 -o root -g traefik traefik/traefik.yml /etc/traefik/traefik.yml.template
$SUDO install -m 0644 systemd/traefik.service /etc/systemd/system/traefik.service

if [ -x ./poolctl ]; then
  $SUDO install -m 0755 ./poolctl /usr/local/bin/poolctl
  $SUDO install -d -m 0755 /opt/poolctl
  $SUDO install -m 0644 systemd/poolctl-guard.service /etc/systemd/system/poolctl-guard.service
  $SUDO install -m 0644 systemd/poolctl-guard.timer /etc/systemd/system/poolctl-guard.timer
fi

$SUDO ufw allow OpenSSH
$SUDO ufw allow 80/tcp
$SUDO ufw allow 443/tcp
$SUDO ufw allow 51820/udp
$SUDO ufw --force enable
ensure_host_ingress_firewall

$SUDO systemctl daemon-reload
migrate_nomad_acl_files
$SUDO systemctl stop traefik 2>/dev/null || true
$SUDO systemctl enable nomad
if ! $SUDO systemctl restart nomad; then
  print_nomad_diagnostics
  die "failed to restart Nomad"
fi
bootstrap_nomad_acl
render_traefik_config
$SUDO systemctl enable traefik
$SUDO systemctl restart traefik
if [ -x /usr/local/bin/poolctl ]; then
  $SUDO systemctl enable --now poolctl-guard.timer
fi
date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ | $SUDO tee "$POOLCTL_READY_MARKER" >/dev/null
$SUDO chmod 0600 "$POOLCTL_READY_MARKER"

echo "Control-plane public IP: %s"
echo "Control-plane overlay IP: %s"
echo "Nomad:  $NOMAD_ADDR"
echo "Traefik: http://%s/"
echo "Bootstrap token: $NOMAD_BOOTSTRAP_TOKEN_FILE"
echo "Done. Run: sudo systemctl status nomad traefik wg-quick@wg0"
`, node.Name, defaultNomadVersion, defaultTraefikVersion, node.OverlayIP, node.OverlayIP, node.OverlayIP, userOrUbuntu(node), node.PublicIP, node.OverlayIP, node.PublicIP)
}

func renderNomadServer(node Node) string {
	return fmt.Sprintf(`name       = "%s"
datacenter = "pool"
data_dir   = "/opt/nomad"
bind_addr  = "%s"

server {
  enabled = true
  bootstrap_expect = 1
}

acl {
  enabled = true
}

tls {
  http                   = true
  rpc                    = true
  ca_file                = "/etc/nomad.d/tls/nomad-agent-ca.pem"
  cert_file              = "/etc/nomad.d/tls/global-server-nomad.pem"
  key_file               = "/etc/nomad.d/tls/global-server-nomad-key.pem"
  verify_server_hostname = true
  verify_https_client    = false
}

client {
  enabled = true
  servers = ["%s:4647"]

  host_network "wireguard" {
    cidr      = "10.44.0.0/24"
    interface = "wg0"
  }
}

plugin "docker" {
  config {
    allow_privileged = false
  }
}
`, node.Name, node.OverlayIP, node.OverlayIP)
}

func renderNomadClient(control, worker Node) string {
	return fmt.Sprintf(`name       = "%s"
datacenter = "pool"
data_dir   = "/opt/nomad"
bind_addr  = "%s"

server {
  enabled = false
}

acl {
  enabled = true
}

tls {
  http                   = true
  rpc                    = true
  ca_file                = "/etc/nomad.d/tls/nomad-agent-ca.pem"
  cert_file              = "/etc/nomad.d/tls/global-client-nomad.pem"
  key_file               = "/etc/nomad.d/tls/global-client-nomad-key.pem"
  verify_server_hostname = true
  verify_https_client    = false
}

client {
  enabled = true
  servers = ["%s:4647"]

  host_network "wireguard" {
    cidr      = "10.44.0.0/24"
    interface = "wg0"
  }
}

plugin "docker" {
  config {
    allow_privileged = false
  }
}
`, worker.Name, worker.OverlayIP, control.OverlayIP)
}

func renderWorkerBootstrapScript(control, worker Node, controlPublicKey string) string {
	return fmt.Sprintf(`#!/usr/bin/env bash
set -Eeuo pipefail

# Generated by poolctl for worker %s.

NOMAD_VERSION="${NOMAD_VERSION:-%s}"
CONTROL_PUBLIC_IP="%s"
CONTROL_OVERLAY_IP="%s"
WORKER_OVERLAY_IP="%s"
CONTROL_WG_PUBLIC_KEY="%s"

die() {
  echo "ERROR: $*" >&2
  exit 1
}

trap 'echo "ERROR: worker bootstrap failed near line $LINENO: $BASH_COMMAND" >&2' ERR

require_root() {
  if [ "$(id -u)" -eq 0 ]; then
    SUDO=""
  else
    SUDO="sudo"
  fi
}

detect_arch() {
  case "$(uname -m)" in
    aarch64|arm64) echo "arm64" ;;
    x86_64|amd64) echo "amd64" ;;
    *) die "unsupported architecture: $(uname -m)" ;;
  esac
}

install_zip_binary() {
  name="$1"
  version="$2"
  url="$3"
  sums_url="$4"
  archive="$5"
  binary="$6"

  tmp_dir="$(mktemp -d)"
  trap 'rm -rf "$tmp_dir"' RETURN

  curl -fsSL "$url" -o "$tmp_dir/$archive"
  curl -fsSL "$sums_url" -o "$tmp_dir/SHA256SUMS"
  (cd "$tmp_dir" && grep "  $archive$" SHA256SUMS | sha256sum -c -) || die "$name checksum verification failed"
  unzip -q "$tmp_dir/$archive" -d "$tmp_dir/$name"
  $SUDO install -m 0755 "$tmp_dir/$name/$binary" "/usr/local/bin/$name"
  "$name" version || true
}

render_wireguard_config() {
  $SUDO install -d -m 0700 /etc/wireguard
  if [ ! -f /etc/wireguard/poolctl-worker.key ]; then
    wg genkey | $SUDO tee /etc/wireguard/poolctl-worker.key >/dev/null
    $SUDO chmod 0600 /etc/wireguard/poolctl-worker.key
  fi
  private_key="$($SUDO cat /etc/wireguard/poolctl-worker.key)"
  $SUDO install -m 0600 /dev/null /etc/wireguard/wg0.conf
  $SUDO tee /etc/wireguard/wg0.conf >/dev/null <<WGEOF
[Interface]
Address = $WORKER_OVERLAY_IP/24
ListenPort = 51820
PrivateKey = $private_key

[Peer]
# %s
PublicKey = $CONTROL_WG_PUBLIC_KEY
AllowedIPs = $CONTROL_OVERLAY_IP/32
Endpoint = $CONTROL_PUBLIC_IP:51820
PersistentKeepalive = 25
WGEOF
  $SUDO systemctl enable wg-quick@wg0
  $SUDO systemctl restart wg-quick@wg0
}

wait_for_wireguard() {
  if [ "${POOLCTL_SKIP_WG_WAIT:-}" = "1" ]; then
    echo "Skipping WireGuard reachability wait; poolctl will verify after control-plane peer update."
    return
  fi
  for _ in $(seq 1 30); do
    if ping -c 1 -W 1 "$CONTROL_OVERLAY_IP" >/dev/null 2>&1; then
      return
    fi
    sleep 2
  done
  echo "---- worker wg show ----"
  $SUDO wg show || true
  echo "---- worker wg0 config ----"
  $SUDO sed -n '1,120p' /etc/wireguard/wg0.conf | sed 's/PrivateKey = .*/PrivateKey = <redacted>/' || true
  echo "---- worker wg0 address ----"
  ip addr show wg0 || true
  echo "---- worker route to control overlay ----"
  ip route get "$CONTROL_OVERLAY_IP" || true
  echo "---- worker public route to control public IP ----"
  ip route get "$CONTROL_PUBLIC_IP" || true
  die "cannot reach control plane WireGuard IP $CONTROL_OVERLAY_IP"
}

require_root
ARCH="$(detect_arch)"

$SUDO apt-get update
$SUDO env DEBIAN_FRONTEND=noninteractive apt-get install -y curl unzip ca-certificates gnupg lsb-release wireguard openssl tar ufw

if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | $SUDO sh
  $SUDO usermod -aG docker %s
fi

$SUDO useradd --system --home /etc/nomad.d --shell /usr/sbin/nologin nomad 2>/dev/null || true

NOMAD_ARCHIVE="nomad_${NOMAD_VERSION}_linux_${ARCH}.zip"
NOMAD_URL="https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/${NOMAD_ARCHIVE}"
NOMAD_SUMS_URL="https://releases.hashicorp.com/nomad/${NOMAD_VERSION}/nomad_${NOMAD_VERSION}_SHA256SUMS"
install_zip_binary "nomad" "$NOMAD_VERSION" "$NOMAD_URL" "$NOMAD_SUMS_URL" "$NOMAD_ARCHIVE" "nomad"

render_wireguard_config
wait_for_wireguard

$SUDO install -d -m 0750 -o nomad -g nomad /etc/nomad.d /etc/nomad.d/tls /opt/nomad
$SUDO install -m 0640 -o nomad -g nomad nomad/client.hcl /etc/nomad.d/client.hcl
$SUDO install -m 0644 systemd/nomad.service /etc/systemd/system/nomad.service
$SUDO install -m 0644 -o nomad -g nomad tls/nomad-agent-ca.pem /etc/nomad.d/tls/nomad-agent-ca.pem
$SUDO install -m 0644 -o nomad -g nomad tls/global-client-nomad.pem /etc/nomad.d/tls/global-client-nomad.pem
$SUDO install -m 0640 -o nomad -g nomad tls/global-client-nomad-key.pem /etc/nomad.d/tls/global-client-nomad-key.pem

$SUDO ufw allow OpenSSH
$SUDO ufw allow in on wg0 from 10.44.0.0/24 to any port 20000:32000 proto tcp
$SUDO ufw --force enable

$SUDO systemctl daemon-reload
$SUDO systemctl enable nomad
$SUDO systemctl restart nomad

echo "Worker: %s"
echo "Worker overlay IP: $WORKER_OVERLAY_IP"
echo "Control overlay IP: $CONTROL_OVERLAY_IP"
echo "Done. Run on control plane: nomad node status"
`, worker.Name, defaultNomadVersion, control.PublicIP, control.OverlayIP, worker.OverlayIP, controlPublicKey, control.Name, userOrUbuntu(worker), worker.Name)
}

func renderTraefikStatic(node Node) string {
	return fmt.Sprintf(`entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  nomad:
    endpoint:
      address: "https://%s:4646"
      token: "__NOMAD_TOKEN__"
      tls:
        ca: "/etc/traefik/nomad-agent-ca.pem"
    exposedByDefault: false

api:
  dashboard: false

certificatesResolvers:
  letsencrypt:
    acme:
      storage: "/var/lib/traefik/acme.json"
      httpChallenge:
        entryPoint: web
`, node.OverlayIP)
}

func renderNomadService() string {
	return `[Unit]
Description=Nomad
Documentation=https://developer.hashicorp.com/nomad/docs
Wants=network-online.target wg-quick@wg0.service docker.service
After=network-online.target wg-quick@wg0.service docker.service

[Service]
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/usr/local/bin/nomad agent -config=/etc/nomad.d
KillMode=process
KillSignal=SIGINT
LimitNOFILE=65536
LimitNPROC=infinity
Restart=on-failure
RestartSec=2
TasksMax=infinity

[Install]
WantedBy=multi-user.target
`
}

func renderTraefikService() string {
	return `[Unit]
Description=Traefik ingress proxy
Documentation=https://doc.traefik.io/traefik/
Wants=network-online.target nomad.service
After=network-online.target nomad.service

[Service]
User=traefik
Group=traefik
ExecStart=/usr/local/bin/traefik --configFile=/etc/traefik/traefik.yml
Restart=on-failure
RestartSec=2
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
`
}

func renderWireGuard(node Node) string {
	return fmt.Sprintf(`# This file is a template. PrivateKey is generated on the server during bootstrap.
[Interface]
Address = %s/24
ListenPort = 51820
PrivateKey = <generated-on-server>

# Worker peers are appended by poolctl join-node.
`, node.OverlayIP)
}

func renderGuardService() string {
	return `[Unit]
Description=poolctl resource guard
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
WorkingDirectory=/opt/poolctl
ExecStart=/usr/local/bin/poolctl guard check
`
}

func renderGuardTimer() string {
	return `[Unit]
Description=Run poolctl resource guard

[Timer]
OnBootSec=2m
OnUnitActiveSec=5m

[Install]
WantedBy=timers.target
`
}

func renderNomadJob(app App) string {
	app = appWithDefaults(app)
	constraints := ""
	if app.PreferNode != "" && !app.AllowWorkers {
		constraints = fmt.Sprintf(`
    constraint {
      attribute = "$${node.unique.name}"
      operator  = "="
      value     = "%s"
    }
`, app.PreferNode)
	}

	return fmt.Sprintf(`job "%s" {
  datacenters = ["pool"]
  type        = "service"

  group "web" {%s
    network {
      port "http" {
        to           = %d
        host_network = "wireguard"
      }
    }

    service {
      name     = "%s"
      provider = "nomad"
      port     = "http"

      tags = [
        "traefik.enable=true",
        "traefik.http.routers.%s.rule=Host(`+"`%s`"+`)",
        "traefik.http.routers.%s.entrypoints=web",
        "traefik.http.routers.%s-secure.rule=Host(`+"`%s`"+`)",
        "traefik.http.routers.%s-secure.entrypoints=websecure",
        "traefik.http.routers.%s-secure.tls=true",
        "traefik.http.routers.%s-secure.tls.certresolver=letsencrypt",
      ]

      check {
        type     = "http"
        path     = "%s"
        interval = "15s"
        timeout  = "3s"
      }
    }

    task "app" {
      driver = "docker"

      config {
        image = "%s"
        ports = ["http"]
      }

      resources {
        cpu    = %d
        memory = %d
      }
    }
  }
}
`, app.Name, constraints, app.Port, app.Name, app.Name, app.Domain, app.Name, app.Name, app.Domain, app.Name, app.Name, app.Name, app.HealthPath, app.Image, app.CPU, app.MemoryMB)
}

func userOrUbuntu(node Node) string {
	if node.SSHUser == "" {
		return "ubuntu"
	}
	return node.SSHUser
}
