package pool

import "fmt"

// SandboxIsolationVersion is written to the host marker file. Bump it when the
// rendered rules change so an operator can tell a stale host from a current one.
const SandboxIsolationVersion = "1"

// SandboxBridgeName is the deterministic Linux bridge backing the sandbox
// Docker network. The firewall rules match on it, so it must not be renamed.
const SandboxBridgeName = "poolctl-sbx0"

// RenderSandboxIsolation renders the host-side isolation bundle for a sandbox
// worker. It is deliberately a separate, reversible bundle rather than a change
// to the control-plane or worker bootstrap: enrolling a sandbox host must never
// require re-running a bootstrap that also touches Nomad, Traefik, or WireGuard.
func RenderSandboxIsolation() []RenderedFile {
	return []RenderedFile{
		{Path: "sandbox/sandbox-isolation.sh", Content: renderSandboxIsolationScript()},
		{Path: "sandbox/README.md", Content: sandboxIsolationReadme},
	}
}

func renderSandboxIsolationScript() string {
	return fmt.Sprintf(`#!/usr/bin/env bash
set -Eeuo pipefail

# Generated by poolctl. Install, verify, or remove sandbox-partition isolation
# on a Myprod worker node.
#
# What this does:
#   1. creates one dedicated Docker bridge network for sandbox partitions;
#   2. installs one firewall chain that constrains only that network.
#
# What this never touches: WireGuard, Nomad, Traefik, sshd, Docker's default
# networks, existing UFW rules, or any other application's connectivity. Every
# rule it adds is tagged with a poolctl comment and removed by --remove.

SANDBOX_NETWORK="%s"
SANDBOX_BRIDGE="%s"
SANDBOX_CIDR="%s"
OVERLAY_CIDR="10.44.0.0/24"
CHAIN="POOLCTL-SANDBOX"
COMMENT="poolctl-sandbox"
MARKER_DIR="/var/lib/poolctl/sandbox"
MARKER_FILE="$MARKER_DIR/isolation.ready"
ISOLATION_VERSION="%s"
SERVICE_FILE="/etc/systemd/system/poolctl-sandbox-isolation.service"
INSTALLED_SCRIPT="/usr/local/sbin/poolctl-sandbox-isolation.sh"
MODE="apply"

# Destinations a sandbox partition may never reach. This is the boundary that
# keeps a compromised or careless sandbox from touching the rest of the pool.
DENY_DESTINATIONS=(
  "$OVERLAY_CIDR"      # WireGuard overlay: Nomad, other nodes, other apps
  "169.254.0.0/16"     # cloud instance metadata and link-local
  "10.0.0.0/8"         # OCI/provider private networks
  "172.16.0.0/12"      # docker networks, including other sandboxes
  "192.168.0.0/16"     # any other private range
  "100.64.0.0/10"      # carrier-grade NAT space
  "127.0.0.0/8"        # loopback
  "224.0.0.0/4"        # multicast
  "240.0.0.0/4"        # reserved
)

usage() {
  cat <<'USAGE'
usage: sandbox-isolation.sh [--apply|--verify|--remove]

  --apply   create the sandbox network and firewall chain (default)
  --verify  report whether isolation is currently installed; change nothing
  --remove  remove the chain, the marker, the unit, and the sandbox network
USAGE
}

die() {
  echo "ERROR: $*" >&2
  exit 1
}

trap 'echo "ERROR: sandbox isolation failed near line $LINENO: $BASH_COMMAND" >&2' ERR

require_root() {
  if [ "$(id -u)" -eq 0 ]; then
    SUDO=""
  else
    SUDO="sudo"
  fi
}

require_tools() {
  command -v docker >/dev/null 2>&1 || die "docker is required"
  command -v iptables >/dev/null 2>&1 || die "iptables is required"
}

refuse_control_plane() {
  # A control-plane node runs Nomad servers, Traefik, the agent, and the pool
  # TLS material. Sandboxes are never allowed to share that machine.
  #
  # Any single indicator is enough to refuse. A control plane whose ready
  # marker was never written, or was removed, must still be refused.
  if $SUDO test -f /etc/traefik/traefik.yml ||
     $SUDO test -d /etc/nomad.d/tls ||
     $SUDO test -f /var/lib/poolctl/control-plane.ready; then
    die "this host is the Myprod control plane; sandbox partitions may only run on workers"
  fi
}

ensure_network() {
  if docker network inspect "$SANDBOX_NETWORK" >/dev/null 2>&1; then
    existing_subnet="$(docker network inspect -f '{{range .IPAM.Config}}{{.Subnet}}{{end}}' "$SANDBOX_NETWORK")"
    if [ "$existing_subnet" != "$SANDBOX_CIDR" ]; then
      die "docker network $SANDBOX_NETWORK exists with subnet $existing_subnet, expected $SANDBOX_CIDR"
    fi
    return
  fi
  $SUDO docker network create \
    --driver bridge \
    --subnet "$SANDBOX_CIDR" \
    --opt "com.docker.network.bridge.name=$SANDBOX_BRIDGE" \
    --opt "com.docker.network.bridge.enable_icc=false" \
    --opt "com.docker.network.bridge.enable_ip_masquerade=true" \
    --label "poolctl.sandbox=true" \
    "$SANDBOX_NETWORK" >/dev/null
}

ensure_chain() {
  $SUDO iptables -N "$CHAIN" 2>/dev/null || true
  $SUDO iptables -F "$CHAIN"

  # Established flows return first so a sandbox can read the responses to the
  # egress it is allowed to make.
  $SUDO iptables -A "$CHAIN" -m conntrack --ctstate RELATED,ESTABLISHED \
    -m comment --comment "$COMMENT-established" -j RETURN

  # Nothing outside the sandbox subnet may open a connection into it.
  $SUDO iptables -A "$CHAIN" -d "$SANDBOX_CIDR" ! -s "$SANDBOX_CIDR" \
    -m conntrack --ctstate NEW -m comment --comment "$COMMENT-no-ingress" -j DROP

  for destination in "${DENY_DESTINATIONS[@]}"; do
    $SUDO iptables -A "$CHAIN" -s "$SANDBOX_CIDR" -d "$destination" \
      -m comment --comment "$COMMENT-deny" -j DROP
  done

  # Defence in depth: scheduler, overlay, and SSH ports on any address.
  $SUDO iptables -A "$CHAIN" -s "$SANDBOX_CIDR" -p tcp -m multiport --dports 4646,4647,4648 \
    -m comment --comment "$COMMENT-deny-nomad" -j DROP
  $SUDO iptables -A "$CHAIN" -s "$SANDBOX_CIDR" -p udp --dport 51820 \
    -m comment --comment "$COMMENT-deny-wireguard" -j DROP
  $SUDO iptables -A "$CHAIN" -s "$SANDBOX_CIDR" -p tcp --dport 22 \
    -m comment --comment "$COMMENT-deny-ssh" -j DROP

  $SUDO iptables -A "$CHAIN" -m comment --comment "$COMMENT-public" -j RETURN

  # Hook the chain from DOCKER-USER, which Docker evaluates before its own
  # forwarding rules. Insert at the top so ordering is deterministic.
  $SUDO iptables -N DOCKER-USER 2>/dev/null || true
  if ! $SUDO iptables -C DOCKER-USER -m comment --comment "$COMMENT-hook" -j "$CHAIN" 2>/dev/null; then
    $SUDO iptables -I DOCKER-USER 1 -m comment --comment "$COMMENT-hook" -j "$CHAIN"
  fi

  # Container-to-host traffic reaches INPUT, not FORWARD, so the bridge is
  # blocked there separately. Sandboxes use public DNS and need nothing local.
  if ! $SUDO iptables -C INPUT -i "$SANDBOX_BRIDGE" -m comment --comment "$COMMENT-host" -j DROP 2>/dev/null; then
    $SUDO iptables -I INPUT 1 -i "$SANDBOX_BRIDGE" -m comment --comment "$COMMENT-host" -j DROP
  fi

  if command -v ip6tables >/dev/null 2>&1; then
    $SUDO ip6tables -C INPUT -i "$SANDBOX_BRIDGE" -m comment --comment "$COMMENT-host" -j DROP 2>/dev/null ||
      $SUDO ip6tables -I INPUT 1 -i "$SANDBOX_BRIDGE" -m comment --comment "$COMMENT-host" -j DROP || true
  fi
}

persist_rules() {
  if command -v netfilter-persistent >/dev/null 2>&1; then
    $SUDO netfilter-persistent save >/dev/null 2>&1 || true
  elif command -v iptables-save >/dev/null 2>&1 && $SUDO test -d /etc/iptables; then
    $SUDO sh -c 'iptables-save > /etc/iptables/rules.v4'
  fi
}

install_service() {
  # Docker rebuilds DOCKER-USER on daemon start, so reapply after boot.
  script_path="$(readlink -f "$0")"
  if [ "$script_path" != "$INSTALLED_SCRIPT" ]; then
    $SUDO install -m 0755 "$script_path" "$INSTALLED_SCRIPT"
  fi
  $SUDO tee "$SERVICE_FILE" >/dev/null <<UNIT
[Unit]
Description=poolctl sandbox partition isolation
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=$INSTALLED_SCRIPT --apply

[Install]
WantedBy=multi-user.target
UNIT
  $SUDO systemctl daemon-reload
  $SUDO systemctl enable poolctl-sandbox-isolation.service >/dev/null 2>&1 || true
}

write_marker() {
  $SUDO mkdir -p "$MARKER_DIR"
  $SUDO chmod 0755 "$MARKER_DIR"
  printf 'version=%%s\nnetwork=%%s\nbridge=%%s\ncidr=%%s\napplied=%%s\n' \
    "$ISOLATION_VERSION" "$SANDBOX_NETWORK" "$SANDBOX_BRIDGE" "$SANDBOX_CIDR" "$(date -u +%%Y-%%m-%%dT%%H:%%M:%%SZ)" |
    $SUDO tee "$MARKER_FILE" >/dev/null
  $SUDO chmod 0644 "$MARKER_FILE"
}

verify() {
  status=0
  if docker network inspect "$SANDBOX_NETWORK" >/dev/null 2>&1; then
    echo "ok      docker network $SANDBOX_NETWORK"
  else
    echo "MISSING docker network $SANDBOX_NETWORK"
    status=1
  fi
  if $SUDO iptables -S "$CHAIN" >/dev/null 2>&1; then
    rules="$($SUDO iptables -S "$CHAIN" | grep -c -- "-j DROP" || true)"
    echo "ok      firewall chain $CHAIN ($rules deny rules)"
  else
    echo "MISSING firewall chain $CHAIN"
    status=1
  fi
  if $SUDO iptables -C DOCKER-USER -m comment --comment "$COMMENT-hook" -j "$CHAIN" 2>/dev/null; then
    echo "ok      DOCKER-USER hook"
  else
    echo "MISSING DOCKER-USER hook"
    status=1
  fi
  if $SUDO iptables -C INPUT -i "$SANDBOX_BRIDGE" -m comment --comment "$COMMENT-host" -j DROP 2>/dev/null; then
    echo "ok      host INPUT block for $SANDBOX_BRIDGE"
  else
    echo "MISSING host INPUT block for $SANDBOX_BRIDGE"
    status=1
  fi
  if $SUDO test -f "$MARKER_FILE"; then
    echo "ok      marker $MARKER_FILE"
    $SUDO cat "$MARKER_FILE" | sed 's/^/        /'
  else
    echo "MISSING marker $MARKER_FILE"
    status=1
  fi
  return "$status"
}

remove() {
  $SUDO iptables -D DOCKER-USER -m comment --comment "$COMMENT-hook" -j "$CHAIN" 2>/dev/null || true
  $SUDO iptables -D INPUT -i "$SANDBOX_BRIDGE" -m comment --comment "$COMMENT-host" -j DROP 2>/dev/null || true
  if command -v ip6tables >/dev/null 2>&1; then
    $SUDO ip6tables -D INPUT -i "$SANDBOX_BRIDGE" -m comment --comment "$COMMENT-host" -j DROP 2>/dev/null || true
  fi
  $SUDO iptables -F "$CHAIN" 2>/dev/null || true
  $SUDO iptables -X "$CHAIN" 2>/dev/null || true
  persist_rules
  $SUDO systemctl disable --now poolctl-sandbox-isolation.service >/dev/null 2>&1 || true
  $SUDO rm -f "$SERVICE_FILE" "$MARKER_FILE"
  $SUDO systemctl daemon-reload >/dev/null 2>&1 || true
  if docker network inspect "$SANDBOX_NETWORK" >/dev/null 2>&1; then
    $SUDO docker network rm "$SANDBOX_NETWORK" >/dev/null 2>&1 ||
      echo "note: $SANDBOX_NETWORK is still in use; destroy running sandboxes first" >&2
  fi
  echo "sandbox isolation removed"
}

case "${1:---apply}" in
  --apply|"") MODE="apply" ;;
  --verify) MODE="verify" ;;
  --remove) MODE="remove" ;;
  -h|--help) usage; exit 0 ;;
  *) usage; exit 64 ;;
esac

require_root
require_tools

case "$MODE" in
  verify) verify ;;
  remove) remove ;;
  apply)
    refuse_control_plane
    ensure_network
    ensure_chain
    persist_rules
    install_service
    write_marker
    echo "sandbox isolation applied"
    verify
    ;;
esac
`, SandboxDockerNetwork, SandboxBridgeName, SandboxNetworkCIDR, SandboxIsolationVersion)
}

const sandboxIsolationReadme = `# Sandbox Host Isolation Bundle

Copy this directory to the worker that will host sandbox partitions and run:

    ./sandbox-isolation.sh --verify   # report current state, change nothing
    ./sandbox-isolation.sh --apply    # install the network and firewall chain
    ./sandbox-isolation.sh --remove   # fully reverse the installation

The script refuses to run on the Myprod control plane. It is additive and
idempotent: every rule it installs carries a ` + "`poolctl-sandbox`" + ` comment and is
removed again by ` + "`--remove`" + `.

After ` + "`--apply`" + ` reports ok, enroll the node from the hosted dashboard or with:

    poolctl sandbox enroll <node> --egress

Only then can a sandbox request network egress. Without the isolation bundle a
node may still be enrolled, but its sandboxes are restricted to
` + "`network: none`" + ` and have no interface other than loopback.
`
